version: '3.8'

services:
  language-teacher-api:
    build:
      context: Backend/LanguageTeacher
      dockerfile: LanguageTeacher/LanguageTeacher.API/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=${ConnectionStrings__MySqlDatabaseConnection}
      - Test=${Test} 
    ports:
      - "5000:80"
      - "5001:443"
    networks:
      - lang-teach-network

networks:
  lang-teach-network:
    driver: bridge