version: '3.8'

services:
  language-teacher-api:
    build:
      context: Backend/LanguageTeacher/LanguageTeacher/LanguageTeacher.API
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_URLS: http://+:80
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5000:80"
      - "5001:443"
    networks:
      - lang-teach-network

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: language_teacher_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - lang-teach-network

networks:
  lang-teach-network:
    driver: bridge

volumes:
  mysql_data: